version: 2

updates:
  - package-ecosystem: gomod 
    directory: "/"
    schedule:
      interval: weekly
      timezone: "Asia/Tokyo"
    labels:
      - dependabot
      - go
    commit-message:
      prefix: "chore(go.mod): "

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      timezone: "Asia/Tokyo"
    labels:
      - dependabot
      - github-actions
    commit-message:
      prefix: "chore(github-actions): "
