version: "2"
linters:
  default: all
  disable:
    - wsl
  settings:
    forbidigo:
      forbid:
        - pattern: "^print(ln)?$"
    mnd:
      ignored-numbers:
        - "0600"
    varnamelen:
      ignore-names:
        - fn
        - err
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
