name: Running golangci-lint to blogctl

on:
  pull_request:
    branches:
      - "*"
    paths:
      - ".github/workflows/test.yml"
      - "cmd/**"
      - "go.mod"
      - "go.sum"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test.yml"
      - "cmd/**"
      - "go.mod"
      - "go.sum"

env:
  GO_VERSION: 1.24.3

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v2.1
